- README.md
Github markdown renders redundant space.
> Fix README (decrease code block indent)

- restclient.el
Hello.
I'm a big fan of restclient.el.
Recently, I've been using it to test some APIs which are only available with session cookie.
Then I found that restclient.el sends cookies, though ```Cookie:``` header wasn't contained in a request buffer.
This is default behavior of ```url-retrieve``` , which is called internally in restclient.el.
I feel it is a bit confusing and there might be some case in which user wants to call API without cookies,
so I'd like to toggle whether to use implicit cookies or not.
> Enable to toggle implicit cookies

- restclient.el
This adds a `restclient-response-loaded-hook` as mentioned in #50. This hook is run after the response buffer has been created and the data loaded into it.
Example usage:
```elisp
(add-hook 'restclient-response-loaded-hook #'view-mode) ;; Enable view-mode minor mode on http responses
```
> Add a restclient-response-loaded-hook.

- restclient.el
I got following  byte-compile warning. This patch fixes this.
```
restclient.el:359:7:Warning: assignment to free variable
`restclient-mode-keywords'
```
> Fix byte-compile warning about using free variable

- restclient.el
The original code failed to parse a JSON string such that 4 or more Hex characters ([0-9a-fA-F])  follow after a unicode character, like `"\u984c1000"` (It represents "題1000").
This change make sure that only 4 characters after `\u` are parsed as a unicode codepoint to fix the issue (opened as #80).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/pashky/restclient.el/79)
> Parse only \u and following 4 characters as a unicode character.

- restclient.el
This is useful for things like, e.g. setting `url-proxy-service' based on proxy configuration.
> Add customization hook prior to running http requests.  

- README.md
Hi there!
My coworker checked out the readme and ran the example and mentioned that headers might not work. Looks like jira doesn't support a xml response. I thought this might be confusing to users that run the examples so I am proposing a change :)
Awesome plugin!
> Update headers example

- restclient.el
`rename-buffer` raises an error if the target buffer already exists.  Kill it first.
> Kill the target buffer if it exists before renaming buffer.

- README.md
The Twitter example used the old API v1 which is not online anymore. Also the new API requires OAuth authentication.
I do realise that you wanted an easy as it get's example on the first line. The Github example doesn't qualify 100% since it also sends a Header. An alternative could be `GET http://jsonip.com`, but I prefered Github, since the API is probably more certain to stay online and accessible.
> Replace obsolete Twitter API example with Github API

- README.md
As discussed in #43 and in #100, GET requests to localhost might fail
due to a bug in Emacs/url.el. This commit documents this as a Known
Issue and adds the workaround of using 127.0.0.1 instead.
> Update README with localhost issues

- helm-restclient.el
- Correct package header
- Load helm-utils for using `helm-goto-line`
- Fix for older Emacs about using `font-lock-ensure`.
There are following byte-compile warnings in original code on Emacs 24.5.
```
helm-restclient.el:72:1:Warning: the following functions are not known to be defined:
font-lock-ensure, helm-goto-line
```
> Fix package

- restclient.el
This is a tiny change to add a hook that runs unconditionally on the raw response buffer. This is in contrast to the existing `restclient-response-loaded-hook` (https://github.com/pashky/restclient.el/pull/61) which runs after the buffer is prettified, if prettifying is on.
The motivating use case was dealing with gzip-formatted binary responses. In order to just get a quick look at what comes back, I can write a function and spike it into the pipeline using this hook. It seems responsive to these other issues: https://github.com/pashky/restclient.el/issues/103 and https://github.com/pashky/restclient.el/issues/140 .
> add hook to operate on raw response, before prettifying

- restclient.el
When receiving a big response with very long lines, restclient crashes with :
```
error in process filter: save-excursion: Stack overflow in regexp matcher
error in process filter: Stack overflow in regexp matcher
```
I figured that restricting a couple of regexp to match a line start fixes the issue, although i'm not 100% sure it's semantically correct.
> Prevent header parsing from crashing with a stack overflow.

- restclient.el
This way keybindings are only defined during load instead of every
time `restclient-mode` is activated. It also allows users to customize
keybindings more easily
> Define keybindings statically

- .gitignore
This should prevent accidental commit of byte-compiled files
and make status more clear for users who obtains restclient.el
mode via Git submodules.
> Add byte-compiled files to ignore list

- restclient.el
This branch adds a method `restclient-toggle-body-visibility` that hides the body of the HTTP request the point is at. If the body is hid, an ellipsis is put at the end of the request line. Calling the same method again shows the body.
In other words, this adds the behaviour of body-visibility-toggling from Org/Outline mode.
For example,
if the point is at `[X]` in the following snippet,
```
POST [X]http://httpbin.org/post
Content-Type: application/json
{
"jql": "project = HSP",
"startAt": 0,
"maxResults": 15,
"fields": [
"summary",
"status",
"assignee"
]
}
```
and TAB is pressed (which calls `restclient-toggle-body-visibility`), the snippet becomes
```
POST [X]http://httpbin.org/post...
```
Pressing TAB again,
```
POST [X]http://httpbin.org/post
Content-Type: application/json
{
"jql": …
```
> Toggle the visibility of HTTP body

- restclient.el
See [RFC 2616 - Section 3.7](https://tools.ietf.org/html/rfc2616#section-3.7)
> Type and subtype in media types should be treated as case insensitive

- restclient.el
Emacs 27 json.el uses `replace-buffer-contents` for pretty-printing which is
great because it keeps point and markers intact but can be very slow with huge
minimalized JSON.  We don't need that feature here because we're at the
beginnning or end of the JSON anyway, so disable it by binding
`json-pretty-print-max-secs` to 0.
> Fast json-pretty-print on Emacs 27

- restclient.el
Introduced the `restclient-response-mode`, which allows response buffer-local keybindings (perhaps its keymap could also be exposed as a customizable variable).
> Introduce response buffer minor mode

- restclient.el
Setting these variables permanently (aka globally) causes them to
affect the behavior of unrelated packages that also use the `url`
library.
By using let-bindings we can limit the effect to a single request.
Re https://github.com/magit/forge/issues/153.
> No longer set url-mime-accept-string et al. permanently

- README.md
- examples/httpbin
- restclient-jq.el
- restclient.el
Hi, 
here's a pull request that adds support for setting variables from responses, it's useful for things like hitting an auth endpoint to get a token.
It's implemented by adding support for per request hooks and an api for setting variables. 
It currently supports running elisp hooks & setting variables from jq expressions if jq-mode is installed
but can be easily extended (in restclient itself or by the end user).
Let me know what you think,
Cameron.
> Support for setting variables from responses

- README.md
The "HSP" project is no longer available at the upstream jira.atlassian.com
host, so the POST example that used that project name in the 'jql' query
stopped working. This change simply replaces "HSP" with "HCPUB", which is a
project ("HipChat") that is still available at that location, so restores the
example to working order.
> fixes #236: README.md: update POST example "HSP" => "HCPUB"

- README.md
Thanks for making this and adding the useful request hook functionality recently.
I wanted to set variables from JSON responses, but can't install jq on my work computer. After playing around  a bit, I found that using the built-in `json-read` is works nicely and is still quite readable for simple parsing.
This PR updates the README to add an example of parsing using Elisp so other users can see how the new request-hooks can still be useful without installing jq or jq-mode.
> Add more useful Elisp example to readme

- restclient-jq.el
- restclient.el
Yesterday's changes broke the package due to these two hanging references, but this has it working for me now
> fix two remaining "resetclient" typos

- README.md
The only existing examples are for GET and don't have a body. My first thought was that the hook would go below the entire request, but that just added it to the body. By trial and error, I discovered that the hook goes here.
This example clarifies where the hook goes if you want to POST.
> Update README with example of hook on POST

- restclient.el
Emacs 28 doesn't seem to load `'cl` by default which breaks the `run-hook` as describe in #248
> Require subr-x and cl package explicitly

- restclient.el
When a URL had any trailing whitespace, the request would needlessly fail.
> Trim URL whitespace so that requests still work correctly

- restclient.el
Hi,
When using `restclient.el` from within Org-mode I frequently found myself having to parse the response from code blocks due to the summary information appended to it (response headers and duration). I thought it would be nice to have a way *not* to include those details if one so wishes. My first idea was to make it conditional upon a customizable variable. Here's a simple change introducing such a variable.
> Allow the omission of response header summary via customizable variable

- restclient-jq.el
There is no lexical-let in cl-lib, it is part of cl, which is deprecated.
Fixes #267
> enable file-level lexical binding

- restclient.el
the previously common practice of rquiring 'cl now throws a
deprecation warning. Update the package requirements to cl-lib.
> 'cl is deprecated in emacs 27 and beyond

- restclient-jq.el
I'm trying to get `restclient-jq` into MELPA, see the [corresponding pull request](https://github.com/melpa/melpa/pull/7982). At MELPA, there is a checklist of automated tests that are supposed to pass before a new package can be included. Here are the relevant bits of MELPA's checklist:
> Prepare restclient jq for inclusion in MELPA

- restclient.el
`cl-lib` does not provide `lexical-let`, making the use of `run-hook` impossible when Emacs Version is higher than 26.
Enabling lexical binding and replacing `lexical-let` occurrences with `let` solves the issue (tested using Emacs 25 and Emacs 29).
> fix: lexical-let is void when using cl-lib

- README.md
- restclient.el
This PR added feature to use `fundamental-mode` when response, received by restclient, is too big (from personal experience, receiving 13kk symbols knocked out my emacs for 5 minutes). Threshold can be tuned via variable (not sure about it's default value though). PR fixes https://github.com/pashky/restclient.el/issues/285
> Display request in fundamental mode if it's too big

- README.md
- restclient.el
This command will send current request as usual but it will not display response buffer.
Motivation: When running http server in the `*shell*` or in `comint` etc. I want to observe log output in that buffer as http request is being processed.
> Added restclient-http-send-current-suppress-response-buffer command
